name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          draft: true

      - name: Generate commit changelog
        id: changelog
        run: |
          git fetch --tags
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ || echo "")
          echo "Previous tag: $PREV_TAG"
          if [ -z "$PREV_TAG" ]; then
            LOG=$(git log --pretty=format:"- %s")
          else
            LOG=$(git log $PREV_TAG..HEAD --pretty=format:"- %s")
          fi
          echo "LOG<<EOF" >> $GITHUB_ENV
          echo "$LOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update Draft Release Notes
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          tag: ${{ steps.release.outputs.tag_name }}
          body: |
            ## What's Changed
            ${{ env.LOG }}
