name: Custom Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # we need full history to generate changelog

      - name: Get last tag
        id: lasttag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump minor version
        id: bump
        run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "${{ steps.lasttag.outputs.tag }}"
          NEW_TAG="$MAJOR.$((MINOR+1)).0"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          PREV_TAG="${{ steps.lasttag.outputs.tag }}"
          NEW_TAG="${{ steps.bump.outputs.new_tag }}"
          if [ "$PREV_TAG" = "0.0.0" ]; then
            LOG=$(git log --pretty=format:"- %s")
          else
            LOG=$(git log $PREV_TAG..HEAD --pretty=format:"- %s")
          fi
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$LOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          name: "Release ${{ steps.bump.outputs.new_tag }}"
          body: |
            ## What's Changed
            ${{ steps.changelog.outputs.log }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
