name: Custom Release
run-name: Production Release Drafter
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # we need full history to generate changelog

      - name: Get last tag
        id: lasttag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump minor version
        id: bump
        run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "${{ steps.lasttag.outputs.tag }}"
          NEW_TAG="$MAJOR.$((MINOR+1)).0"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          PREV_TAG="${{ steps.lasttag.outputs.tag }}"
          NEW_TAG="${{ steps.bump.outputs.new_tag }}"
          if [ "$PREV_TAG" = "0.0.0" ]; then
            LOG=$(git log --pretty=format:"- %s (%an)")
          else
            LOG=$(git log $PREV_TAG..HEAD --pretty=format:"- %s (%an)")
          fi
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$LOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create draft release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          name: "🚀 Release ${{ steps.bump.outputs.new_tag }}"
          body: |
            ## Release Notes
            <!-- add any release notes here -->

            ## 🔥 What's Changed
            ${{ steps.changelog.outputs.log }}

            ---
            
            ## 📋 Full Changelog
            🔗 **[View all changes →](https://github.com/${{ github.repository }}/compare/${{ steps.lasttag.outputs.tag }}...${{ steps.bump.outputs.new_tag }})**
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Send Draft Release URL to Slack   
        run: |
          # Get release approvers from GitHub variables (JSON format)
          RELEASE_APPROVERS='${{ vars.RELEASE_APPROVERS }}'
          
          # Extract all Slack IDs from JSON and format as mentions
          SLACK_MENTIONS=$(echo "$RELEASE_APPROVERS" | jq -r 'to_entries | .[] | "<@" + .value + ">"' | tr '\n' ' ')
          
          # Format the mention text with all approvers
          MENTION_TEXT="$SLACK_MENTIONS please review this draft release and approve! 🎯 \n\n {{ steps.release.outputs.url }}"
          
          curl -X POST -H 'Content-type: application/json' \
           --data "{\"text\":\"🚀 *New Draft Release Created*\n\n📋 **Release**: ${{ steps.bump.outputs.new_tag }}\n🔗 **Draft URL**: ${{ steps.release.outputs.url }}\n\n\n\n$MENTION_TEXT\"}" \
            ${{ secrets.SLACK_WEBHOOK }}
